export const legalBaseTypes = [
  'CONTRACT',
  'CONSENT',
  'LEGITIMATE-INTEREST',
  'NECESSARY',
  'NECESSARY.LEGAL-OBLIGATION',
  'NECESSARY.PUBLIC-INTEREST',
  'NECESSARY.VITAL-INTEREST',
  'OTHER-LEGAL-BASE',
];
