export const processingCategories = [
  '*',
  'ANONYMIZATION',
  'AUTOMATED-INFERENCE',
  'AUTOMATED-DECISION-MAKING',
  'COLLECTION',
  'GENERATING',
  'PUBLISHING',
  'STORING',
  'SHARING',
  'USING',
  'OTHER-PROCESSING',
];
