name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_STAGING }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"

deploy-to-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    name: Build and Deploy Job
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_PRODUCTION }}
          app_location: "/"
          api_location: ""
          output_location: "build"