name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - develop
      - main

jobs:
  deploy-to-dev:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    name: Deploy staging
    env:
      REACT_APP_API_URL: https://stage.identity.devkit.blindnet.io
      REACT_APP_PCE_API_URL: https://stage.computing.blindnet.io
      REACT_APP_STORAGE_API_URL: https://stage.storage.blindnet.io
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_STAGING }}
          action: "upload"
          app_location: "/"
          api_location: ""
          output_location: "build"

  deploy-to-prod:
      if: github.ref == 'refs/heads/main'
      runs-on: ubuntu-latest
      name: Deploy production
      env:
        REACT_APP_API_URL: https://identity.devkit.blindnet.io
        REACT_APP_PCE_API_URL: https://computing.blindnet.io
        REACT_APP_STORAGE_API_URL: https://storage.blindnet.io
      steps:
        - uses: actions/checkout@v2
          with:
            submodules: true
        - name: Build And Deploy
          uses: Azure/static-web-apps-deploy@v1
          with:
            azure_static_web_apps_api_token: ${{ secrets.AZURE_TOKEN_PRODUCTION }}
            action: "upload"
            app_location: "/"
            api_location: ""
            output_location: "build"